# Generated by Django 4.0.2 on 2022-02-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_gallery', '0002_remove_gallery_images_imggallery_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='imggallery',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
