# Generated by Django 4.0.2 on 2022-02-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_gallery', '0003_alter_gallery_title_alter_imggallery_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='count_img',
        ),
        migrations.AlterField(
            model_name='imggallery',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='care_gallery.gallery'),
        ),
    ]
