# Generated by Django 4.0.2 on 2022-02-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_gallery', '0006_gallery_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='parent',
        ),
    ]
