# Generated by Django 4.0.2 on 2022-02-22 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_gallery', '0010_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
