# Generated by Django 4.0.2 on 2022-02-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_gallery', '0016_gallery_images_remove_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['-id']},
        ),
    ]
